# Generated by Django 5.2.12 on 2026-07-14 22:01

import django.utils.timezone
from django.db import migrations, models


def populate_booking_metadata(apps, schema_editor):
    Booking = apps.get_model('parking', 'Booking')
    Vehicle = apps.get_model('parking', 'Vehicle')
    for booking in Booking.objects.all():
        if booking.vehicle_id is not None:
            try:
                vehicle = Vehicle.objects.get(pk=booking.vehicle_id)
                booking.vehicle_number = vehicle.number_plate
            except Vehicle.DoesNotExist:
                booking.vehicle_number = ''
        if not booking.booking_id:
            booking.booking_id = f'BK-LEGACY-{booking.pk}'
        if booking.slot_id is not None:
            booking.parking_lot_id = booking.slot.parking_lot_id
        booking.save(update_fields=['vehicle_number', 'booking_id', 'parking_lot'])


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_seed_default_parking_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='car', max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Slot',
            new_name='ParkingSlot',
        ),
        migrations.RenameField(
            model_name='parkingslot',
            old_name='lot',
            new_name='parking_lot',
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='description',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='opening_hours',
            field=models.CharField(default='24/7', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='security_rating',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='price_hint',
            field=models.DecimalField(default=0, decimal_places=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='distance_km',
            field=models.DecimalField(default=0, decimal_places=2, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='walking_time_minutes',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_ev_charging',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_covered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='is_24x7',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='map_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='image_url',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='recommended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='facilities',
            field=models.ManyToManyField(blank=True, to='parking.Facility'),
        ),
        migrations.AddField(
            model_name='parkinglot',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='parking.VehicleType'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='vehicles', to='parking.VehicleType'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, to='parking.VehicleType'),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='reserved', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, auto_now=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='parking_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='bookings', to='parking.ParkingLot'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.PROTECT, related_name='bookings', to='parking.VehicleType'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=models.CASCADE, related_name='history', to='parking.Booking')),
            ],
        ),
        migrations.RunPython(populate_booking_metadata, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='booking',
            name='vehicle',
        ),
    ]
